
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.minekpop.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import net.mcreator.minekpop.item.Yuqi5Item;
import net.mcreator.minekpop.item.Yuqi4Item;
import net.mcreator.minekpop.item.Yuqi3Item;
import net.mcreator.minekpop.item.Yuqi2Item;
import net.mcreator.minekpop.item.Yuqi1Item;
import net.mcreator.minekpop.item.Yeonjun5Item;
import net.mcreator.minekpop.item.Yeonjun4Item;
import net.mcreator.minekpop.item.Yeonjun3Item;
import net.mcreator.minekpop.item.Yeonjun2Item;
import net.mcreator.minekpop.item.Yeonjun1Item;
import net.mcreator.minekpop.item.WifegidleItem;
import net.mcreator.minekpop.item.V4Item;
import net.mcreator.minekpop.item.V3Item;
import net.mcreator.minekpop.item.V2Item;
import net.mcreator.minekpop.item.V1Item;
import net.mcreator.minekpop.item.UnforgivenLeSserafimItem;
import net.mcreator.minekpop.item.Taehyun5Item;
import net.mcreator.minekpop.item.Taehyun4Item;
import net.mcreator.minekpop.item.Taehyun3Item;
import net.mcreator.minekpop.item.Taehyun2Item;
import net.mcreator.minekpop.item.Taehyun1Item;
import net.mcreator.minekpop.item.TXTTheDreamChapterStarItem;
import net.mcreator.minekpop.item.TXTLightstickItem;
import net.mcreator.minekpop.item.TXTBlueHourItem;
import net.mcreator.minekpop.item.TXT9Item;
import net.mcreator.minekpop.item.TXT8Item;
import net.mcreator.minekpop.item.TXT7Item;
import net.mcreator.minekpop.item.TXT6Item;
import net.mcreator.minekpop.item.TXT5Item;
import net.mcreator.minekpop.item.TXT4Item;
import net.mcreator.minekpop.item.TXT3Item;
import net.mcreator.minekpop.item.TXT2Item;
import net.mcreator.minekpop.item.TXT1Item;
import net.mcreator.minekpop.item.Suga5Item;
import net.mcreator.minekpop.item.Suga4Item;
import net.mcreator.minekpop.item.Suga3Item;
import net.mcreator.minekpop.item.Suga2Item;
import net.mcreator.minekpop.item.Suga1Item;
import net.mcreator.minekpop.item.StrayKidsMaxIdentItem;
import net.mcreator.minekpop.item.StrayKidsLightstickItem;
import net.mcreator.minekpop.item.StrayKids5StarsItem;
import net.mcreator.minekpop.item.StrayKids2Item;
import net.mcreator.minekpop.item.StrayKids1Item;
import net.mcreator.minekpop.item.Soyeon6Item;
import net.mcreator.minekpop.item.Soyeon5Item;
import net.mcreator.minekpop.item.Soyeon4Item;
import net.mcreator.minekpop.item.Soyeon3Item;
import net.mcreator.minekpop.item.Soyeon2Item;
import net.mcreator.minekpop.item.Soyeon1Item;
import net.mcreator.minekpop.item.Soojin4Item;
import net.mcreator.minekpop.item.Soojin3Item;
import net.mcreator.minekpop.item.Soojin2Item;
import net.mcreator.minekpop.item.Soojin1Item;
import net.mcreator.minekpop.item.Soobin5Item;
import net.mcreator.minekpop.item.Soobin4Item;
import net.mcreator.minekpop.item.Soobin3Item;
import net.mcreator.minekpop.item.Soobin2Item;
import net.mcreator.minekpop.item.Soobin1Item;
import net.mcreator.minekpop.item.SmartLeSerafimItem;
import net.mcreator.minekpop.item.SlumpSKZItem;
import net.mcreator.minekpop.item.SilentCrySKZItem;
import net.mcreator.minekpop.item.Shuhua4Item;
import net.mcreator.minekpop.item.Shuhua3Item;
import net.mcreator.minekpop.item.Shuhua2Item;
import net.mcreator.minekpop.item.Shuhua1Item;
import net.mcreator.minekpop.item.Seungmin4Item;
import net.mcreator.minekpop.item.Seungmin3Item;
import net.mcreator.minekpop.item.Seungmin2Item;
import net.mcreator.minekpop.item.Seungmin1Item;
import net.mcreator.minekpop.item.Sakura4Item;
import net.mcreator.minekpop.item.Sakura3Item;
import net.mcreator.minekpop.item.Sakura2Item;
import net.mcreator.minekpop.item.Sakura1Item;
import net.mcreator.minekpop.item.RM4Item;
import net.mcreator.minekpop.item.RM3Item;
import net.mcreator.minekpop.item.RM2Item;
import net.mcreator.minekpop.item.RM1Item;
import net.mcreator.minekpop.item.QueencardGIdleItem;
import net.mcreator.minekpop.item.PerfectNightLeSserafimItem;
import net.mcreator.minekpop.item.NocelestialLeSserafimItem;
import net.mcreator.minekpop.item.Miyeon4Item;
import net.mcreator.minekpop.item.Miyeon3Item;
import net.mcreator.minekpop.item.Miyeon2Item;
import net.mcreator.minekpop.item.Miyeon1Item;
import net.mcreator.minekpop.item.Minnie5Item;
import net.mcreator.minekpop.item.Minnie4Item;
import net.mcreator.minekpop.item.Minnie3Item;
import net.mcreator.minekpop.item.Minnie2Item;
import net.mcreator.minekpop.item.Minnie1Item;
import net.mcreator.minekpop.item.LoveSongTXTItem;
import net.mcreator.minekpop.item.LesserafimLightstickItem;
import net.mcreator.minekpop.item.LeeKnow4Item;
import net.mcreator.minekpop.item.LeeKnow3Item;
import net.mcreator.minekpop.item.LeeKnow2Item;
import net.mcreator.minekpop.item.LeeKnow1Item;
import net.mcreator.minekpop.item.LeSserafimPerfectNightItem;
import net.mcreator.minekpop.item.LeSserafimFCB3Item;
import net.mcreator.minekpop.item.LeSserafimFCB2Item;
import net.mcreator.minekpop.item.LeSserafimFCB1Item;
import net.mcreator.minekpop.item.LeSserafimF1Item;
import net.mcreator.minekpop.item.LeSserafimAlbumItem;
import net.mcreator.minekpop.item.LeSserafimAlbum2Item;
import net.mcreator.minekpop.item.LeSserafim2Item;
import net.mcreator.minekpop.item.LeSserafim1Item;
import net.mcreator.minekpop.item.LadyGidleItem;
import net.mcreator.minekpop.item.Kazuha4Item;
import net.mcreator.minekpop.item.Kazuha3Item;
import net.mcreator.minekpop.item.Kazuha2Item;
import net.mcreator.minekpop.item.Kazuha1Item;
import net.mcreator.minekpop.item.Junjin4Item;
import net.mcreator.minekpop.item.Junjin3Item;
import net.mcreator.minekpop.item.Junjin2Item;
import net.mcreator.minekpop.item.Junjin1Item;
import net.mcreator.minekpop.item.JungKook5Item;
import net.mcreator.minekpop.item.JungKook4Item;
import net.mcreator.minekpop.item.JungKook3Item;
import net.mcreator.minekpop.item.JungKook2Item;
import net.mcreator.minekpop.item.JungKook1Item;
import net.mcreator.minekpop.item.Jin4Item;
import net.mcreator.minekpop.item.Jin3Item;
import net.mcreator.minekpop.item.Jin2Item;
import net.mcreator.minekpop.item.Jin1Item;
import net.mcreator.minekpop.item.Jimin5Item;
import net.mcreator.minekpop.item.Jimin4Item;
import net.mcreator.minekpop.item.Jimin3Item;
import net.mcreator.minekpop.item.Jimin2Item;
import net.mcreator.minekpop.item.Jimin1Item;
import net.mcreator.minekpop.item.JHope4Item;
import net.mcreator.minekpop.item.JHope3Item;
import net.mcreator.minekpop.item.JHope2Item;
import net.mcreator.minekpop.item.JHope1Item;
import net.mcreator.minekpop.item.IWantThatGidleItem;
import net.mcreator.minekpop.item.IN4Item;
import net.mcreator.minekpop.item.IN3Item;
import net.mcreator.minekpop.item.IN2Item;
import net.mcreator.minekpop.item.IN1Item;
import net.mcreator.minekpop.item.Hyunjin4Item;
import net.mcreator.minekpop.item.Hyunjin3Item;
import net.mcreator.minekpop.item.Hyunjin2Item;
import net.mcreator.minekpop.item.Hyunjin1Item;
import net.mcreator.minekpop.item.HueningKai5Item;
import net.mcreator.minekpop.item.HueningKai4Item;
import net.mcreator.minekpop.item.HueningKai3Item;
import net.mcreator.minekpop.item.HueningKai2Item;
import net.mcreator.minekpop.item.HueningKai1Item;
import net.mcreator.minekpop.item.HellevatorSKZItem;
import net.mcreator.minekpop.item.Han4Item;
import net.mcreator.minekpop.item.Han3Item;
import net.mcreator.minekpop.item.Han2Item;
import net.mcreator.minekpop.item.Han1Item;
import net.mcreator.minekpop.item.GIdleLightstickItem;
import net.mcreator.minekpop.item.GIdleIfeel2Item;
import net.mcreator.minekpop.item.GIdleIfeel1Item;
import net.mcreator.minekpop.item.GIdle7Item;
import net.mcreator.minekpop.item.GIdle6Item;
import net.mcreator.minekpop.item.GIdle5Item;
import net.mcreator.minekpop.item.GIdle4Item;
import net.mcreator.minekpop.item.GIdle3Item;
import net.mcreator.minekpop.item.GIdle2Item;
import net.mcreator.minekpop.item.GIdle1Item;
import net.mcreator.minekpop.item.FireInTheBellyLeSserafimItem;
import net.mcreator.minekpop.item.Felix4Item;
import net.mcreator.minekpop.item.Felix3Item;
import net.mcreator.minekpop.item.Felix2Item;
import net.mcreator.minekpop.item.Felix1Item;
import net.mcreator.minekpop.item.FategidleItem;
import net.mcreator.minekpop.item.EyesRollGidleItem;
import net.mcreator.minekpop.item.EvepsychethebluebeardswifeItem;
import net.mcreator.minekpop.item.Eunchae4Item;
import net.mcreator.minekpop.item.Eunchae3Item;
import net.mcreator.minekpop.item.Eunchae2Item;
import net.mcreator.minekpop.item.Eunchae1Item;
import net.mcreator.minekpop.item.EasyLeSserafimItem;
import net.mcreator.minekpop.item.CheeseSKZItem;
import net.mcreator.minekpop.item.Changbin4Item;
import net.mcreator.minekpop.item.Changbin3Item;
import net.mcreator.minekpop.item.Changbin2Item;
import net.mcreator.minekpop.item.Changbin1Item;
import net.mcreator.minekpop.item.Chan4Item;
import net.mcreator.minekpop.item.Chan3Item;
import net.mcreator.minekpop.item.Chan2Item;
import net.mcreator.minekpop.item.Chan1Item;
import net.mcreator.minekpop.item.ChaewonRabbitItem;
import net.mcreator.minekpop.item.ChaewonLakersItem;
import net.mcreator.minekpop.item.ChaewonFCB3Item;
import net.mcreator.minekpop.item.ChaewonFCB2Item;
import net.mcreator.minekpop.item.ChaewonFCB1Item;
import net.mcreator.minekpop.item.Chaewon6Item;
import net.mcreator.minekpop.item.Chaewon5Item;
import net.mcreator.minekpop.item.Chaewon4Item;
import net.mcreator.minekpop.item.Chaewon3Item;
import net.mcreator.minekpop.item.Chaewon2Item;
import net.mcreator.minekpop.item.Chaewon1Item;
import net.mcreator.minekpop.item.BtsYouNeverWalkAloneItem;
import net.mcreator.minekpop.item.BtsLoveYourselfItem;
import net.mcreator.minekpop.item.Beomgyu5Item;
import net.mcreator.minekpop.item.Beomgyu4Item;
import net.mcreator.minekpop.item.Beomgyu3Item;
import net.mcreator.minekpop.item.Beomgyu2Item;
import net.mcreator.minekpop.item.Beomgyu1Item;
import net.mcreator.minekpop.item.BTSLightstickItem;
import net.mcreator.minekpop.item.BTS2Item;
import net.mcreator.minekpop.item.BTS1Item;
import net.mcreator.minekpop.item.BT21Item;
import net.mcreator.minekpop.item.AntifragileLeSserafimItem;
import net.mcreator.minekpop.MineKpopMod;

public class MineKpopModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MineKpopMod.MODID);
	public static final RegistryObject<Item> LESSERAFIM_LIGHTSTICK = REGISTRY.register("lesserafim_lightstick", () -> new LesserafimLightstickItem());
	public static final RegistryObject<Item> STRAY_KIDS_LIGHTSTICK = REGISTRY.register("stray_kids_lightstick", () -> new StrayKidsLightstickItem());
	public static final RegistryObject<Item> BTS_LIGHTSTICK = REGISTRY.register("bts_lightstick", () -> new BTSLightstickItem());
	public static final RegistryObject<Item> G_IDLE_LIGHTSTICK = REGISTRY.register("g_idle_lightstick", () -> new GIdleLightstickItem());
	public static final RegistryObject<Item> TXT_LIGHTSTICK = REGISTRY.register("txt_lightstick", () -> new TXTLightstickItem());
	public static final RegistryObject<Item> LE_SSERAFIM_ALBUM = REGISTRY.register("le_sserafim_album", () -> new LeSserafimAlbumItem());
	public static final RegistryObject<Item> LE_SSERAFIM_ALBUM_2 = REGISTRY.register("le_sserafim_album_2", () -> new LeSserafimAlbum2Item());
	public static final RegistryObject<Item> STRAY_KIDS_5_STARS = REGISTRY.register("stray_kids_5_stars", () -> new StrayKids5StarsItem());
	public static final RegistryObject<Item> STRAY_KIDS_MAX_IDENT = REGISTRY.register("stray_kids_max_ident", () -> new StrayKidsMaxIdentItem());
	public static final RegistryObject<Item> BTS_LOVE_YOURSELF = REGISTRY.register("bts_love_yourself", () -> new BtsLoveYourselfItem());
	public static final RegistryObject<Item> BTS_YOU_NEVER_WALK_ALONE = REGISTRY.register("bts_you_never_walk_alone", () -> new BtsYouNeverWalkAloneItem());
	public static final RegistryObject<Item> G_IDLE_IFEEL_1 = REGISTRY.register("g_idle_ifeel_1", () -> new GIdleIfeel1Item());
	public static final RegistryObject<Item> G_IDLE_IFEEL_2 = REGISTRY.register("g_idle_ifeel_2", () -> new GIdleIfeel2Item());
	public static final RegistryObject<Item> TXT_BLUE_HOUR = REGISTRY.register("txt_blue_hour", () -> new TXTBlueHourItem());
	public static final RegistryObject<Item> TXT_THE_DREAM_CHAPTER_STAR = REGISTRY.register("txt_the_dream_chapter_star", () -> new TXTTheDreamChapterStarItem());
	public static final RegistryObject<Item> CHAEWON_1 = REGISTRY.register("chaewon_1", () -> new Chaewon1Item());
	public static final RegistryObject<Item> CHAEWON_2 = REGISTRY.register("chaewon_2", () -> new Chaewon2Item());
	public static final RegistryObject<Item> CHAEWON_3 = REGISTRY.register("chaewon_3", () -> new Chaewon3Item());
	public static final RegistryObject<Item> CHAEWON_4 = REGISTRY.register("chaewon_4", () -> new Chaewon4Item());
	public static final RegistryObject<Item> CHAEWON_5 = REGISTRY.register("chaewon_5", () -> new Chaewon5Item());
	public static final RegistryObject<Item> CHAEWON_FCB_1 = REGISTRY.register("chaewon_fcb_1", () -> new ChaewonFCB1Item());
	public static final RegistryObject<Item> CHAEWON_FCB_2 = REGISTRY.register("chaewon_fcb_2", () -> new ChaewonFCB2Item());
	public static final RegistryObject<Item> CHAEWON_FCB_3 = REGISTRY.register("chaewon_fcb_3", () -> new ChaewonFCB3Item());
	public static final RegistryObject<Item> EUNCHAE_1 = REGISTRY.register("eunchae_1", () -> new Eunchae1Item());
	public static final RegistryObject<Item> EUNCHAE_2 = REGISTRY.register("eunchae_2", () -> new Eunchae2Item());
	public static final RegistryObject<Item> EUNCHAE_3 = REGISTRY.register("eunchae_3", () -> new Eunchae3Item());
	public static final RegistryObject<Item> EUNCHAE_4 = REGISTRY.register("eunchae_4", () -> new Eunchae4Item());
	public static final RegistryObject<Item> JUNJIN_1 = REGISTRY.register("junjin_1", () -> new Junjin1Item());
	public static final RegistryObject<Item> JUNJIN_2 = REGISTRY.register("junjin_2", () -> new Junjin2Item());
	public static final RegistryObject<Item> JUNJIN_3 = REGISTRY.register("junjin_3", () -> new Junjin3Item());
	public static final RegistryObject<Item> JUNJIN_4 = REGISTRY.register("junjin_4", () -> new Junjin4Item());
	public static final RegistryObject<Item> KAZUHA_1 = REGISTRY.register("kazuha_1", () -> new Kazuha1Item());
	public static final RegistryObject<Item> KAZUHA_2 = REGISTRY.register("kazuha_2", () -> new Kazuha2Item());
	public static final RegistryObject<Item> KAZUHA_3 = REGISTRY.register("kazuha_3", () -> new Kazuha3Item());
	public static final RegistryObject<Item> KAZUHA_4 = REGISTRY.register("kazuha_4", () -> new Kazuha4Item());
	public static final RegistryObject<Item> LE_SSERAFIM_1 = REGISTRY.register("le_sserafim_1", () -> new LeSserafim1Item());
	public static final RegistryObject<Item> LE_SSERAFIM_F_1 = REGISTRY.register("le_sserafim_f_1", () -> new LeSserafimF1Item());
	public static final RegistryObject<Item> LE_SSERAFIM_FCB_1 = REGISTRY.register("le_sserafim_fcb_1", () -> new LeSserafimFCB1Item());
	public static final RegistryObject<Item> LE_SSERAFIM_FCB_2 = REGISTRY.register("le_sserafim_fcb_2", () -> new LeSserafimFCB2Item());
	public static final RegistryObject<Item> LE_SSERAFIM_FCB_3 = REGISTRY.register("le_sserafim_fcb_3", () -> new LeSserafimFCB3Item());
	public static final RegistryObject<Item> LE_SSERAFIM_PERFECT_NIGHT = REGISTRY.register("le_sserafim_perfect_night", () -> new LeSserafimPerfectNightItem());
	public static final RegistryObject<Item> SAKURA_1 = REGISTRY.register("sakura_1", () -> new Sakura1Item());
	public static final RegistryObject<Item> SAKURA_2 = REGISTRY.register("sakura_2", () -> new Sakura2Item());
	public static final RegistryObject<Item> SAKURA_3 = REGISTRY.register("sakura_3", () -> new Sakura3Item());
	public static final RegistryObject<Item> SAKURA_4 = REGISTRY.register("sakura_4", () -> new Sakura4Item());
	public static final RegistryObject<Item> CHAEWON_LAKERS = REGISTRY.register("chaewon_lakers", () -> new ChaewonLakersItem());
	public static final RegistryObject<Item> CHAEWON_RABBIT = REGISTRY.register("chaewon_rabbit", () -> new ChaewonRabbitItem());
	public static final RegistryObject<Item> CHAEWON_6 = REGISTRY.register("chaewon_6", () -> new Chaewon6Item());
	public static final RegistryObject<Item> LE_SSERAFIM_2 = REGISTRY.register("le_sserafim_2", () -> new LeSserafim2Item());
	public static final RegistryObject<Item> CHAN_1 = REGISTRY.register("chan_1", () -> new Chan1Item());
	public static final RegistryObject<Item> CHAN_2 = REGISTRY.register("chan_2", () -> new Chan2Item());
	public static final RegistryObject<Item> CHAN_3 = REGISTRY.register("chan_3", () -> new Chan3Item());
	public static final RegistryObject<Item> CHAN_4 = REGISTRY.register("chan_4", () -> new Chan4Item());
	public static final RegistryObject<Item> CHANGBIN_1 = REGISTRY.register("changbin_1", () -> new Changbin1Item());
	public static final RegistryObject<Item> CHANGBIN_2 = REGISTRY.register("changbin_2", () -> new Changbin2Item());
	public static final RegistryObject<Item> CHANGBIN_3 = REGISTRY.register("changbin_3", () -> new Changbin3Item());
	public static final RegistryObject<Item> CHANGBIN_4 = REGISTRY.register("changbin_4", () -> new Changbin4Item());
	public static final RegistryObject<Item> FELIX_1 = REGISTRY.register("felix_1", () -> new Felix1Item());
	public static final RegistryObject<Item> FELIX_2 = REGISTRY.register("felix_2", () -> new Felix2Item());
	public static final RegistryObject<Item> FELIX_3 = REGISTRY.register("felix_3", () -> new Felix3Item());
	public static final RegistryObject<Item> FELIX_4 = REGISTRY.register("felix_4", () -> new Felix4Item());
	public static final RegistryObject<Item> HAN_1 = REGISTRY.register("han_1", () -> new Han1Item());
	public static final RegistryObject<Item> HAN_2 = REGISTRY.register("han_2", () -> new Han2Item());
	public static final RegistryObject<Item> HAN_3 = REGISTRY.register("han_3", () -> new Han3Item());
	public static final RegistryObject<Item> HAN_4 = REGISTRY.register("han_4", () -> new Han4Item());
	public static final RegistryObject<Item> HYUNJIN_1 = REGISTRY.register("hyunjin_1", () -> new Hyunjin1Item());
	public static final RegistryObject<Item> HYUNJIN_2 = REGISTRY.register("hyunjin_2", () -> new Hyunjin2Item());
	public static final RegistryObject<Item> HYUNJIN_3 = REGISTRY.register("hyunjin_3", () -> new Hyunjin3Item());
	public static final RegistryObject<Item> HYUNJIN_4 = REGISTRY.register("hyunjin_4", () -> new Hyunjin4Item());
	public static final RegistryObject<Item> IN_1 = REGISTRY.register("in_1", () -> new IN1Item());
	public static final RegistryObject<Item> IN_2 = REGISTRY.register("in_2", () -> new IN2Item());
	public static final RegistryObject<Item> IN_3 = REGISTRY.register("in_3", () -> new IN3Item());
	public static final RegistryObject<Item> IN_4 = REGISTRY.register("in_4", () -> new IN4Item());
	public static final RegistryObject<Item> LEE_KNOW_1 = REGISTRY.register("lee_know_1", () -> new LeeKnow1Item());
	public static final RegistryObject<Item> LEE_KNOW_2 = REGISTRY.register("lee_know_2", () -> new LeeKnow2Item());
	public static final RegistryObject<Item> LEE_KNOW_3 = REGISTRY.register("lee_know_3", () -> new LeeKnow3Item());
	public static final RegistryObject<Item> LEE_KNOW_4 = REGISTRY.register("lee_know_4", () -> new LeeKnow4Item());
	public static final RegistryObject<Item> SEUNGMIN_1 = REGISTRY.register("seungmin_1", () -> new Seungmin1Item());
	public static final RegistryObject<Item> SEUNGMIN_2 = REGISTRY.register("seungmin_2", () -> new Seungmin2Item());
	public static final RegistryObject<Item> SEUNGMIN_3 = REGISTRY.register("seungmin_3", () -> new Seungmin3Item());
	public static final RegistryObject<Item> SEUNGMIN_4 = REGISTRY.register("seungmin_4", () -> new Seungmin4Item());
	public static final RegistryObject<Item> STRAY_KIDS_1 = REGISTRY.register("stray_kids_1", () -> new StrayKids1Item());
	public static final RegistryObject<Item> STRAY_KIDS_2 = REGISTRY.register("stray_kids_2", () -> new StrayKids2Item());
	public static final RegistryObject<Item> J_HOPE_1 = REGISTRY.register("j_hope_1", () -> new JHope1Item());
	public static final RegistryObject<Item> J_HOPE_2 = REGISTRY.register("j_hope_2", () -> new JHope2Item());
	public static final RegistryObject<Item> J_HOPE_3 = REGISTRY.register("j_hope_3", () -> new JHope3Item());
	public static final RegistryObject<Item> J_HOPE_4 = REGISTRY.register("j_hope_4", () -> new JHope4Item());
	public static final RegistryObject<Item> JIMIN_1 = REGISTRY.register("jimin_1", () -> new Jimin1Item());
	public static final RegistryObject<Item> JIMIN_2 = REGISTRY.register("jimin_2", () -> new Jimin2Item());
	public static final RegistryObject<Item> JIMIN_3 = REGISTRY.register("jimin_3", () -> new Jimin3Item());
	public static final RegistryObject<Item> JIMIN_4 = REGISTRY.register("jimin_4", () -> new Jimin4Item());
	public static final RegistryObject<Item> JIMIN_5 = REGISTRY.register("jimin_5", () -> new Jimin5Item());
	public static final RegistryObject<Item> JIN_1 = REGISTRY.register("jin_1", () -> new Jin1Item());
	public static final RegistryObject<Item> JIN_2 = REGISTRY.register("jin_2", () -> new Jin2Item());
	public static final RegistryObject<Item> JIN_3 = REGISTRY.register("jin_3", () -> new Jin3Item());
	public static final RegistryObject<Item> JIN_4 = REGISTRY.register("jin_4", () -> new Jin4Item());
	public static final RegistryObject<Item> JUNG_KOOK_1 = REGISTRY.register("jung_kook_1", () -> new JungKook1Item());
	public static final RegistryObject<Item> JUNG_KOOK_2 = REGISTRY.register("jung_kook_2", () -> new JungKook2Item());
	public static final RegistryObject<Item> JUNG_KOOK_3 = REGISTRY.register("jung_kook_3", () -> new JungKook3Item());
	public static final RegistryObject<Item> JUNG_KOOK_4 = REGISTRY.register("jung_kook_4", () -> new JungKook4Item());
	public static final RegistryObject<Item> JUNG_KOOK_5 = REGISTRY.register("jung_kook_5", () -> new JungKook5Item());
	public static final RegistryObject<Item> RM_1 = REGISTRY.register("rm_1", () -> new RM1Item());
	public static final RegistryObject<Item> RM_2 = REGISTRY.register("rm_2", () -> new RM2Item());
	public static final RegistryObject<Item> RM_3 = REGISTRY.register("rm_3", () -> new RM3Item());
	public static final RegistryObject<Item> RM_4 = REGISTRY.register("rm_4", () -> new RM4Item());
	public static final RegistryObject<Item> SUGA_1 = REGISTRY.register("suga_1", () -> new Suga1Item());
	public static final RegistryObject<Item> SUGA_2 = REGISTRY.register("suga_2", () -> new Suga2Item());
	public static final RegistryObject<Item> SUGA_3 = REGISTRY.register("suga_3", () -> new Suga3Item());
	public static final RegistryObject<Item> SUGA_4 = REGISTRY.register("suga_4", () -> new Suga4Item());
	public static final RegistryObject<Item> SUGA_5 = REGISTRY.register("suga_5", () -> new Suga5Item());
	public static final RegistryObject<Item> V_1 = REGISTRY.register("v_1", () -> new V1Item());
	public static final RegistryObject<Item> V_2 = REGISTRY.register("v_2", () -> new V2Item());
	public static final RegistryObject<Item> V_3 = REGISTRY.register("v_3", () -> new V3Item());
	public static final RegistryObject<Item> V_4 = REGISTRY.register("v_4", () -> new V4Item());
	public static final RegistryObject<Item> BTS_1 = REGISTRY.register("bts_1", () -> new BTS1Item());
	public static final RegistryObject<Item> BTS_2 = REGISTRY.register("bts_2", () -> new BTS2Item());
	public static final RegistryObject<Item> BT_21 = REGISTRY.register("bt_21", () -> new BT21Item());
	public static final RegistryObject<Item> MINNIE_1 = REGISTRY.register("minnie_1", () -> new Minnie1Item());
	public static final RegistryObject<Item> MINNIE_2 = REGISTRY.register("minnie_2", () -> new Minnie2Item());
	public static final RegistryObject<Item> MINNIE_3 = REGISTRY.register("minnie_3", () -> new Minnie3Item());
	public static final RegistryObject<Item> MINNIE_4 = REGISTRY.register("minnie_4", () -> new Minnie4Item());
	public static final RegistryObject<Item> MINNIE_5 = REGISTRY.register("minnie_5", () -> new Minnie5Item());
	public static final RegistryObject<Item> MIYEON_1 = REGISTRY.register("miyeon_1", () -> new Miyeon1Item());
	public static final RegistryObject<Item> MIYEON_2 = REGISTRY.register("miyeon_2", () -> new Miyeon2Item());
	public static final RegistryObject<Item> MIYEON_3 = REGISTRY.register("miyeon_3", () -> new Miyeon3Item());
	public static final RegistryObject<Item> MIYEON_4 = REGISTRY.register("miyeon_4", () -> new Miyeon4Item());
	public static final RegistryObject<Item> SHUHUA_1 = REGISTRY.register("shuhua_1", () -> new Shuhua1Item());
	public static final RegistryObject<Item> SHUHUA_2 = REGISTRY.register("shuhua_2", () -> new Shuhua2Item());
	public static final RegistryObject<Item> SHUHUA_3 = REGISTRY.register("shuhua_3", () -> new Shuhua3Item());
	public static final RegistryObject<Item> SHUHUA_4 = REGISTRY.register("shuhua_4", () -> new Shuhua4Item());
	public static final RegistryObject<Item> SOOJIN_1 = REGISTRY.register("soojin_1", () -> new Soojin1Item());
	public static final RegistryObject<Item> SOOJIN_2 = REGISTRY.register("soojin_2", () -> new Soojin2Item());
	public static final RegistryObject<Item> SOOJIN_3 = REGISTRY.register("soojin_3", () -> new Soojin3Item());
	public static final RegistryObject<Item> SOOJIN_4 = REGISTRY.register("soojin_4", () -> new Soojin4Item());
	public static final RegistryObject<Item> SOYEON_1 = REGISTRY.register("soyeon_1", () -> new Soyeon1Item());
	public static final RegistryObject<Item> SOYEON_2 = REGISTRY.register("soyeon_2", () -> new Soyeon2Item());
	public static final RegistryObject<Item> SOYEON_3 = REGISTRY.register("soyeon_3", () -> new Soyeon3Item());
	public static final RegistryObject<Item> SOYEON_4 = REGISTRY.register("soyeon_4", () -> new Soyeon4Item());
	public static final RegistryObject<Item> SOYEON_5 = REGISTRY.register("soyeon_5", () -> new Soyeon5Item());
	public static final RegistryObject<Item> SOYEON_6 = REGISTRY.register("soyeon_6", () -> new Soyeon6Item());
	public static final RegistryObject<Item> YUQI_1 = REGISTRY.register("yuqi_1", () -> new Yuqi1Item());
	public static final RegistryObject<Item> YUQI_2 = REGISTRY.register("yuqi_2", () -> new Yuqi2Item());
	public static final RegistryObject<Item> YUQI_3 = REGISTRY.register("yuqi_3", () -> new Yuqi3Item());
	public static final RegistryObject<Item> YUQI_4 = REGISTRY.register("yuqi_4", () -> new Yuqi4Item());
	public static final RegistryObject<Item> YUQI_5 = REGISTRY.register("yuqi_5", () -> new Yuqi5Item());
	public static final RegistryObject<Item> G_IDLE_1 = REGISTRY.register("g_idle_1", () -> new GIdle1Item());
	public static final RegistryObject<Item> G_IDLE_2 = REGISTRY.register("g_idle_2", () -> new GIdle2Item());
	public static final RegistryObject<Item> G_IDLE_3 = REGISTRY.register("g_idle_3", () -> new GIdle3Item());
	public static final RegistryObject<Item> G_IDLE_4 = REGISTRY.register("g_idle_4", () -> new GIdle4Item());
	public static final RegistryObject<Item> G_IDLE_5 = REGISTRY.register("g_idle_5", () -> new GIdle5Item());
	public static final RegistryObject<Item> G_IDLE_6 = REGISTRY.register("g_idle_6", () -> new GIdle6Item());
	public static final RegistryObject<Item> G_IDLE_7 = REGISTRY.register("g_idle_7", () -> new GIdle7Item());
	public static final RegistryObject<Item> BEOMGYU_1 = REGISTRY.register("beomgyu_1", () -> new Beomgyu1Item());
	public static final RegistryObject<Item> BEOMGYU_2 = REGISTRY.register("beomgyu_2", () -> new Beomgyu2Item());
	public static final RegistryObject<Item> BEOMGYU_3 = REGISTRY.register("beomgyu_3", () -> new Beomgyu3Item());
	public static final RegistryObject<Item> BEOMGYU_4 = REGISTRY.register("beomgyu_4", () -> new Beomgyu4Item());
	public static final RegistryObject<Item> BEOMGYU_5 = REGISTRY.register("beomgyu_5", () -> new Beomgyu5Item());
	public static final RegistryObject<Item> HUENING_KAI_1 = REGISTRY.register("huening_kai_1", () -> new HueningKai1Item());
	public static final RegistryObject<Item> HUENING_KAI_2 = REGISTRY.register("huening_kai_2", () -> new HueningKai2Item());
	public static final RegistryObject<Item> HUENING_KAI_3 = REGISTRY.register("huening_kai_3", () -> new HueningKai3Item());
	public static final RegistryObject<Item> HUENING_KAI_4 = REGISTRY.register("huening_kai_4", () -> new HueningKai4Item());
	public static final RegistryObject<Item> HUENING_KAI_5 = REGISTRY.register("huening_kai_5", () -> new HueningKai5Item());
	public static final RegistryObject<Item> SOOBIN_1 = REGISTRY.register("soobin_1", () -> new Soobin1Item());
	public static final RegistryObject<Item> SOOBIN_2 = REGISTRY.register("soobin_2", () -> new Soobin2Item());
	public static final RegistryObject<Item> SOOBIN_3 = REGISTRY.register("soobin_3", () -> new Soobin3Item());
	public static final RegistryObject<Item> SOOBIN_4 = REGISTRY.register("soobin_4", () -> new Soobin4Item());
	public static final RegistryObject<Item> SOOBIN_5 = REGISTRY.register("soobin_5", () -> new Soobin5Item());
	public static final RegistryObject<Item> TAEHYUN_1 = REGISTRY.register("taehyun_1", () -> new Taehyun1Item());
	public static final RegistryObject<Item> TAEHYUN_2 = REGISTRY.register("taehyun_2", () -> new Taehyun2Item());
	public static final RegistryObject<Item> TAEHYUN_3 = REGISTRY.register("taehyun_3", () -> new Taehyun3Item());
	public static final RegistryObject<Item> TAEHYUN_4 = REGISTRY.register("taehyun_4", () -> new Taehyun4Item());
	public static final RegistryObject<Item> TAEHYUN_5 = REGISTRY.register("taehyun_5", () -> new Taehyun5Item());
	public static final RegistryObject<Item> YEONJUN_1 = REGISTRY.register("yeonjun_1", () -> new Yeonjun1Item());
	public static final RegistryObject<Item> YEONJUN_2 = REGISTRY.register("yeonjun_2", () -> new Yeonjun2Item());
	public static final RegistryObject<Item> YEONJUN_3 = REGISTRY.register("yeonjun_3", () -> new Yeonjun3Item());
	public static final RegistryObject<Item> YEONJUN_4 = REGISTRY.register("yeonjun_4", () -> new Yeonjun4Item());
	public static final RegistryObject<Item> YEONJUN_5 = REGISTRY.register("yeonjun_5", () -> new Yeonjun5Item());
	public static final RegistryObject<Item> TXT_1 = REGISTRY.register("txt_1", () -> new TXT1Item());
	public static final RegistryObject<Item> TXT_2 = REGISTRY.register("txt_2", () -> new TXT2Item());
	public static final RegistryObject<Item> TXT_3 = REGISTRY.register("txt_3", () -> new TXT3Item());
	public static final RegistryObject<Item> TXT_4 = REGISTRY.register("txt_4", () -> new TXT4Item());
	public static final RegistryObject<Item> TXT_5 = REGISTRY.register("txt_5", () -> new TXT5Item());
	public static final RegistryObject<Item> TXT_6 = REGISTRY.register("txt_6", () -> new TXT6Item());
	public static final RegistryObject<Item> TXT_7 = REGISTRY.register("txt_7", () -> new TXT7Item());
	public static final RegistryObject<Item> TXT_8 = REGISTRY.register("txt_8", () -> new TXT8Item());
	public static final RegistryObject<Item> TXT_9 = REGISTRY.register("txt_9", () -> new TXT9Item());
	public static final RegistryObject<Item> SMART_LE_SERAFIM = REGISTRY.register("smart_le_serafim", () -> new SmartLeSerafimItem());
	public static final RegistryObject<Item> EASY_LE_SSERAFIM = REGISTRY.register("easy_le_sserafim", () -> new EasyLeSserafimItem());
	public static final RegistryObject<Item> NOCELESTIAL_LE_SSERAFIM = REGISTRY.register("nocelestial_le_sserafim", () -> new NocelestialLeSserafimItem());
	public static final RegistryObject<Item> FIRE_IN_THE_BELLY_LE_SSERAFIM = REGISTRY.register("fire_in_the_belly_le_sserafim", () -> new FireInTheBellyLeSserafimItem());
	public static final RegistryObject<Item> UNFORGIVEN_LE_SSERAFIM = REGISTRY.register("unforgiven_le_sserafim", () -> new UnforgivenLeSserafimItem());
	public static final RegistryObject<Item> PERFECT_NIGHT_LE_SSERAFIM = REGISTRY.register("perfect_night_le_sserafim", () -> new PerfectNightLeSserafimItem());
	public static final RegistryObject<Item> ANTIFRAGILE_LE_SSERAFIM = REGISTRY.register("antifragile_le_sserafim", () -> new AntifragileLeSserafimItem());
	public static final RegistryObject<Item> EVEPSYCHETHEBLUEBEARDSWIFE = REGISTRY.register("evepsychethebluebeardswife", () -> new EvepsychethebluebeardswifeItem());
	public static final RegistryObject<Item> QUEENCARD_G_IDLE = REGISTRY.register("queencard_g_idle", () -> new QueencardGIdleItem());
	public static final RegistryObject<Item> FATEGIDLE = REGISTRY.register("fategidle", () -> new FategidleItem());
	public static final RegistryObject<Item> LADY_GIDLE = REGISTRY.register("lady_gidle", () -> new LadyGidleItem());
	public static final RegistryObject<Item> WIFEGIDLE = REGISTRY.register("wifegidle", () -> new WifegidleItem());
	public static final RegistryObject<Item> I_WANT_THAT_GIDLE = REGISTRY.register("i_want_that_gidle", () -> new IWantThatGidleItem());
	public static final RegistryObject<Item> EYES_ROLL_GIDLE = REGISTRY.register("eyes_roll_gidle", () -> new EyesRollGidleItem());
	public static final RegistryObject<Item> LOVE_SONG_TXT = REGISTRY.register("love_song_txt", () -> new LoveSongTXTItem());
	public static final RegistryObject<Item> SLUMP_SKZ = REGISTRY.register("slump_skz", () -> new SlumpSKZItem());
	public static final RegistryObject<Item> SILENT_CRY_SKZ = REGISTRY.register("silent_cry_skz", () -> new SilentCrySKZItem());
	public static final RegistryObject<Item> CHEESE_SKZ = REGISTRY.register("cheese_skz", () -> new CheeseSKZItem());
	public static final RegistryObject<Item> HELLEVATOR_SKZ = REGISTRY.register("hellevator_skz", () -> new HellevatorSKZItem());
}
