
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.minekpop.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import net.mcreator.minekpop.item.StrayKidsMaxIdentItem;
import net.mcreator.minekpop.item.StrayKidsLightstickItem;
import net.mcreator.minekpop.item.StrayKids5StarsItem;
import net.mcreator.minekpop.item.StrayKids2Item;
import net.mcreator.minekpop.item.StrayKids1Item;
import net.mcreator.minekpop.item.Seungmin4Item;
import net.mcreator.minekpop.item.Seungmin3Item;
import net.mcreator.minekpop.item.Seungmin2Item;
import net.mcreator.minekpop.item.Seungmin1Item;
import net.mcreator.minekpop.item.Sakura4Item;
import net.mcreator.minekpop.item.Sakura3Item;
import net.mcreator.minekpop.item.Sakura2Item;
import net.mcreator.minekpop.item.Sakura1Item;
import net.mcreator.minekpop.item.LesserafimLightstickItem;
import net.mcreator.minekpop.item.LeeKnow4Item;
import net.mcreator.minekpop.item.LeeKnow3Item;
import net.mcreator.minekpop.item.LeeKnow2Item;
import net.mcreator.minekpop.item.LeeKnow1Item;
import net.mcreator.minekpop.item.LeSserafimPerfectNightItem;
import net.mcreator.minekpop.item.LeSserafimFCB3Item;
import net.mcreator.minekpop.item.LeSserafimFCB2Item;
import net.mcreator.minekpop.item.LeSserafimFCB1Item;
import net.mcreator.minekpop.item.LeSserafimF1Item;
import net.mcreator.minekpop.item.LeSserafimAlbumItem;
import net.mcreator.minekpop.item.LeSserafimAlbum2Item;
import net.mcreator.minekpop.item.LeSserafim2Item;
import net.mcreator.minekpop.item.LeSserafim1Item;
import net.mcreator.minekpop.item.Kazuha4Item;
import net.mcreator.minekpop.item.Kazuha3Item;
import net.mcreator.minekpop.item.Kazuha2Item;
import net.mcreator.minekpop.item.Kazuha1Item;
import net.mcreator.minekpop.item.Junjin4Item;
import net.mcreator.minekpop.item.Junjin3Item;
import net.mcreator.minekpop.item.Junjin2Item;
import net.mcreator.minekpop.item.Junjin1Item;
import net.mcreator.minekpop.item.IN4Item;
import net.mcreator.minekpop.item.IN3Item;
import net.mcreator.minekpop.item.IN2Item;
import net.mcreator.minekpop.item.IN1Item;
import net.mcreator.minekpop.item.Hyunjin4Item;
import net.mcreator.minekpop.item.Hyunjin3Item;
import net.mcreator.minekpop.item.Hyunjin2Item;
import net.mcreator.minekpop.item.Hyunjin1Item;
import net.mcreator.minekpop.item.Han4Item;
import net.mcreator.minekpop.item.Han3Item;
import net.mcreator.minekpop.item.Han2Item;
import net.mcreator.minekpop.item.Han1Item;
import net.mcreator.minekpop.item.Felix4Item;
import net.mcreator.minekpop.item.Felix3Item;
import net.mcreator.minekpop.item.Felix2Item;
import net.mcreator.minekpop.item.Felix1Item;
import net.mcreator.minekpop.item.Eunchae4Item;
import net.mcreator.minekpop.item.Eunchae3Item;
import net.mcreator.minekpop.item.Eunchae2Item;
import net.mcreator.minekpop.item.Eunchae1Item;
import net.mcreator.minekpop.item.Changbin4Item;
import net.mcreator.minekpop.item.Changbin3Item;
import net.mcreator.minekpop.item.Changbin2Item;
import net.mcreator.minekpop.item.Changbin1Item;
import net.mcreator.minekpop.item.Chan4Item;
import net.mcreator.minekpop.item.Chan3Item;
import net.mcreator.minekpop.item.Chan2Item;
import net.mcreator.minekpop.item.Chan1Item;
import net.mcreator.minekpop.item.ChaewonRabbitItem;
import net.mcreator.minekpop.item.ChaewonLakersItem;
import net.mcreator.minekpop.item.ChaewonFCB3Item;
import net.mcreator.minekpop.item.ChaewonFCB2Item;
import net.mcreator.minekpop.item.ChaewonFCB1Item;
import net.mcreator.minekpop.item.Chaewon6Item;
import net.mcreator.minekpop.item.Chaewon5Item;
import net.mcreator.minekpop.item.Chaewon4Item;
import net.mcreator.minekpop.item.Chaewon3Item;
import net.mcreator.minekpop.item.Chaewon2Item;
import net.mcreator.minekpop.item.Chaewon1Item;
import net.mcreator.minekpop.MineKpopMod;

public class MineKpopModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MineKpopMod.MODID);
	public static final RegistryObject<Item> LESSERAFIM_LIGHTSTICK = REGISTRY.register("lesserafim_lightstick", () -> new LesserafimLightstickItem());
	public static final RegistryObject<Item> LE_SSERAFIM_ALBUM = REGISTRY.register("le_sserafim_album", () -> new LeSserafimAlbumItem());
	public static final RegistryObject<Item> LE_SSERAFIM_ALBUM_2 = REGISTRY.register("le_sserafim_album_2", () -> new LeSserafimAlbum2Item());
	public static final RegistryObject<Item> CHAEWON_1 = REGISTRY.register("chaewon_1", () -> new Chaewon1Item());
	public static final RegistryObject<Item> CHAEWON_2 = REGISTRY.register("chaewon_2", () -> new Chaewon2Item());
	public static final RegistryObject<Item> CHAEWON_3 = REGISTRY.register("chaewon_3", () -> new Chaewon3Item());
	public static final RegistryObject<Item> CHAEWON_4 = REGISTRY.register("chaewon_4", () -> new Chaewon4Item());
	public static final RegistryObject<Item> CHAEWON_5 = REGISTRY.register("chaewon_5", () -> new Chaewon5Item());
	public static final RegistryObject<Item> CHAEWON_FCB_1 = REGISTRY.register("chaewon_fcb_1", () -> new ChaewonFCB1Item());
	public static final RegistryObject<Item> CHAEWON_FCB_2 = REGISTRY.register("chaewon_fcb_2", () -> new ChaewonFCB2Item());
	public static final RegistryObject<Item> CHAEWON_FCB_3 = REGISTRY.register("chaewon_fcb_3", () -> new ChaewonFCB3Item());
	public static final RegistryObject<Item> EUNCHAE_1 = REGISTRY.register("eunchae_1", () -> new Eunchae1Item());
	public static final RegistryObject<Item> EUNCHAE_2 = REGISTRY.register("eunchae_2", () -> new Eunchae2Item());
	public static final RegistryObject<Item> EUNCHAE_3 = REGISTRY.register("eunchae_3", () -> new Eunchae3Item());
	public static final RegistryObject<Item> EUNCHAE_4 = REGISTRY.register("eunchae_4", () -> new Eunchae4Item());
	public static final RegistryObject<Item> JUNJIN_1 = REGISTRY.register("junjin_1", () -> new Junjin1Item());
	public static final RegistryObject<Item> JUNJIN_2 = REGISTRY.register("junjin_2", () -> new Junjin2Item());
	public static final RegistryObject<Item> JUNJIN_3 = REGISTRY.register("junjin_3", () -> new Junjin3Item());
	public static final RegistryObject<Item> JUNJIN_4 = REGISTRY.register("junjin_4", () -> new Junjin4Item());
	public static final RegistryObject<Item> KAZUHA_1 = REGISTRY.register("kazuha_1", () -> new Kazuha1Item());
	public static final RegistryObject<Item> KAZUHA_2 = REGISTRY.register("kazuha_2", () -> new Kazuha2Item());
	public static final RegistryObject<Item> KAZUHA_3 = REGISTRY.register("kazuha_3", () -> new Kazuha3Item());
	public static final RegistryObject<Item> KAZUHA_4 = REGISTRY.register("kazuha_4", () -> new Kazuha4Item());
	public static final RegistryObject<Item> LE_SSERAFIM_1 = REGISTRY.register("le_sserafim_1", () -> new LeSserafim1Item());
	public static final RegistryObject<Item> LE_SSERAFIM_F_1 = REGISTRY.register("le_sserafim_f_1", () -> new LeSserafimF1Item());
	public static final RegistryObject<Item> LE_SSERAFIM_FCB_1 = REGISTRY.register("le_sserafim_fcb_1", () -> new LeSserafimFCB1Item());
	public static final RegistryObject<Item> LE_SSERAFIM_FCB_2 = REGISTRY.register("le_sserafim_fcb_2", () -> new LeSserafimFCB2Item());
	public static final RegistryObject<Item> LE_SSERAFIM_FCB_3 = REGISTRY.register("le_sserafim_fcb_3", () -> new LeSserafimFCB3Item());
	public static final RegistryObject<Item> LE_SSERAFIM_PERFECT_NIGHT = REGISTRY.register("le_sserafim_perfect_night", () -> new LeSserafimPerfectNightItem());
	public static final RegistryObject<Item> SAKURA_1 = REGISTRY.register("sakura_1", () -> new Sakura1Item());
	public static final RegistryObject<Item> SAKURA_2 = REGISTRY.register("sakura_2", () -> new Sakura2Item());
	public static final RegistryObject<Item> SAKURA_3 = REGISTRY.register("sakura_3", () -> new Sakura3Item());
	public static final RegistryObject<Item> SAKURA_4 = REGISTRY.register("sakura_4", () -> new Sakura4Item());
	public static final RegistryObject<Item> CHAEWON_LAKERS = REGISTRY.register("chaewon_lakers", () -> new ChaewonLakersItem());
	public static final RegistryObject<Item> CHAEWON_RABBIT = REGISTRY.register("chaewon_rabbit", () -> new ChaewonRabbitItem());
	public static final RegistryObject<Item> CHAEWON_6 = REGISTRY.register("chaewon_6", () -> new Chaewon6Item());
	public static final RegistryObject<Item> LE_SSERAFIM_2 = REGISTRY.register("le_sserafim_2", () -> new LeSserafim2Item());
	public static final RegistryObject<Item> STRAY_KIDS_5_STARS = REGISTRY.register("stray_kids_5_stars", () -> new StrayKids5StarsItem());
	public static final RegistryObject<Item> STRAY_KIDS_LIGHTSTICK = REGISTRY.register("stray_kids_lightstick", () -> new StrayKidsLightstickItem());
	public static final RegistryObject<Item> CHAN_1 = REGISTRY.register("chan_1", () -> new Chan1Item());
	public static final RegistryObject<Item> CHAN_2 = REGISTRY.register("chan_2", () -> new Chan2Item());
	public static final RegistryObject<Item> CHAN_3 = REGISTRY.register("chan_3", () -> new Chan3Item());
	public static final RegistryObject<Item> CHAN_4 = REGISTRY.register("chan_4", () -> new Chan4Item());
	public static final RegistryObject<Item> CHANGBIN_1 = REGISTRY.register("changbin_1", () -> new Changbin1Item());
	public static final RegistryObject<Item> CHANGBIN_2 = REGISTRY.register("changbin_2", () -> new Changbin2Item());
	public static final RegistryObject<Item> CHANGBIN_3 = REGISTRY.register("changbin_3", () -> new Changbin3Item());
	public static final RegistryObject<Item> CHANGBIN_4 = REGISTRY.register("changbin_4", () -> new Changbin4Item());
	public static final RegistryObject<Item> FELIX_1 = REGISTRY.register("felix_1", () -> new Felix1Item());
	public static final RegistryObject<Item> FELIX_2 = REGISTRY.register("felix_2", () -> new Felix2Item());
	public static final RegistryObject<Item> FELIX_3 = REGISTRY.register("felix_3", () -> new Felix3Item());
	public static final RegistryObject<Item> FELIX_4 = REGISTRY.register("felix_4", () -> new Felix4Item());
	public static final RegistryObject<Item> HAN_1 = REGISTRY.register("han_1", () -> new Han1Item());
	public static final RegistryObject<Item> HAN_2 = REGISTRY.register("han_2", () -> new Han2Item());
	public static final RegistryObject<Item> HAN_3 = REGISTRY.register("han_3", () -> new Han3Item());
	public static final RegistryObject<Item> HAN_4 = REGISTRY.register("han_4", () -> new Han4Item());
	public static final RegistryObject<Item> HYUNJIN_1 = REGISTRY.register("hyunjin_1", () -> new Hyunjin1Item());
	public static final RegistryObject<Item> HYUNJIN_2 = REGISTRY.register("hyunjin_2", () -> new Hyunjin2Item());
	public static final RegistryObject<Item> HYUNJIN_3 = REGISTRY.register("hyunjin_3", () -> new Hyunjin3Item());
	public static final RegistryObject<Item> HYUNJIN_4 = REGISTRY.register("hyunjin_4", () -> new Hyunjin4Item());
	public static final RegistryObject<Item> IN_1 = REGISTRY.register("in_1", () -> new IN1Item());
	public static final RegistryObject<Item> IN_2 = REGISTRY.register("in_2", () -> new IN2Item());
	public static final RegistryObject<Item> IN_3 = REGISTRY.register("in_3", () -> new IN3Item());
	public static final RegistryObject<Item> IN_4 = REGISTRY.register("in_4", () -> new IN4Item());
	public static final RegistryObject<Item> LEE_KNOW_1 = REGISTRY.register("lee_know_1", () -> new LeeKnow1Item());
	public static final RegistryObject<Item> LEE_KNOW_2 = REGISTRY.register("lee_know_2", () -> new LeeKnow2Item());
	public static final RegistryObject<Item> LEE_KNOW_3 = REGISTRY.register("lee_know_3", () -> new LeeKnow3Item());
	public static final RegistryObject<Item> LEE_KNOW_4 = REGISTRY.register("lee_know_4", () -> new LeeKnow4Item());
	public static final RegistryObject<Item> SEUNGMIN_1 = REGISTRY.register("seungmin_1", () -> new Seungmin1Item());
	public static final RegistryObject<Item> SEUNGMIN_2 = REGISTRY.register("seungmin_2", () -> new Seungmin2Item());
	public static final RegistryObject<Item> SEUNGMIN_3 = REGISTRY.register("seungmin_3", () -> new Seungmin3Item());
	public static final RegistryObject<Item> SEUNGMIN_4 = REGISTRY.register("seungmin_4", () -> new Seungmin4Item());
	public static final RegistryObject<Item> STRAY_KIDS_MAX_IDENT = REGISTRY.register("stray_kids_max_ident", () -> new StrayKidsMaxIdentItem());
	public static final RegistryObject<Item> STRAY_KIDS_1 = REGISTRY.register("stray_kids_1", () -> new StrayKids1Item());
	public static final RegistryObject<Item> STRAY_KIDS_2 = REGISTRY.register("stray_kids_2", () -> new StrayKids2Item());
}
